from .dhmd import DHMD
from .htw import HTW
from .internationale_gaerten import InternationaleGaerten
from .japanisches_palais import JapanischesPalais
from .kinokalender import Kinokalender
from .lokale_agenda import LokaleAgenda
from .medienkulturzentrum import Medienkulturzentrum
from .slub import SLUB
from .stura import StuRa
from .tu_dresden import TUDresden
from .verbraucherzentrale import Verbraucherzentrale